// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPsrpg2BvmctAjOg-qL_87EkfgApbCWmw',
    appId: '1:939930035190:web:8afc1a9e1184ce3bca9dd7',
    messagingSenderId: '939930035190',
    projectId: 'fir-hw4-7c570',
    authDomain: 'fir-hw4-7c570.firebaseapp.com',
    storageBucket: 'fir-hw4-7c570.firebasestorage.app',
    measurementId: 'G-WJ419Y72HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV5IWjl8a0My4UuVgTCKkeAT6SX6bTsJc',
    appId: '1:939930035190:android:c9bc96737b5a0705ca9dd7',
    messagingSenderId: '939930035190',
    projectId: 'fir-hw4-7c570',
    storageBucket: 'fir-hw4-7c570.firebasestorage.app',
  );
}
